### ISSUE TITLE
有个apk，里面是有lib目录的。

### ISSUE THREAD

**Issue by kirin233x** [nszdhd1/UtilScript#1]
Traceback (most recent call last):
  File ".\LIEFInjectFrida.py", line 121, in <module>
    out = liefs.modifyapk()
  File ".\LIEFInjectFrida.py", line 74, in modifyapk
    shutil.rmtree("lib")
  File "C:\Program Files\Python38\lib\shutil.py", line 730, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python38\lib\shutil.py", line 589, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Program Files\Python38\lib\shutil.py", line 586, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'lib'

**Comment by nszdhd1** [comment]
运行过程中会在os.getcwd()路径下产生一个名为lib的中间文件，可能是你shell路径和运行路径不一致
