### ISSUE TITLE
sign apk error

### ISSUE THREAD

**Issue by zqebaby** [nszdhd1/UtilScript#2]
Hi master, I meet the following trouble when I sign the apk , plz help~ many thx

java env:
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment Homebrew (build 19.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.1, mixed mode, sharing)

os:
Darwin Kernel Version 21.2.0  arm64

java -jar tools/apksignerNew.jar sign --kstools/APPkeystore.jks --ks-key-alias key0 --ks-pass pass:qwer1234 --key-pass pass:qwer1234 --out ./tools/test_frida_Signed.apk ./tools/test_frida.apk
Exception in thread "main" java.lang.IllegalAccessError: class com.android.apksig.internal.apk.v1.V1SchemeSigner (in unnamed module @0x54307ae0) cannot access class sun.security.x509.AlgorithmId (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x54307ae0
	at com.android.apksig.internal.apk.v1.V1SchemeSigner.getSupportedAlgorithmId(V1SchemeSigner.java:622)
	at com.android.apksig.internal.apk.v1.V1SchemeSigner.<clinit>(V1SchemeSigner.java:538)
	at com.android.apksig.DefaultApkSignerEngine.<init>(DefaultApkSignerEngine.java:146)
	at com.android.apksig.DefaultApkSignerEngine.<init>(DefaultApkSignerEngine.java:51)
	at com.android.apksig.DefaultApkSignerEngine$Builder.build(DefaultApkSignerEngine.java:899)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:280)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:93)

**Comment by nszdhd1** [comment]
Your jdk version is too high，Use OpenJDK 8. Java 9 is causing this problem
